GET http://localhost:3333/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGVkcm8iLCJpYXQiOjE3MjE2ODM5MTh9.oMZBzfBn24MqONBNINhWpeHjA8Av64l2oJlDVPcMaRE

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "Test",
    "email": "e@mail.com",
    "password": "123321"
}

###

POST http://localhost:3333/login
Content-Type: application/json

{
    "email": "e@mail.com",
    "password": "123321"
}