GET http://localhost:3333/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiUGVkcm8iLCJpYXQiOjE3MjE2ODM5MTh9.oMZBzfBn24MqONBNINhWpeHjA8Av64l2oJlDVPcMaRE

###

POST http://localhost:3333/collectors
Content-Type: application/json

{
    "name": "Pedro",
    "email": "pedro@email.com",
    "password": "123321",
    "birthdate": "1995-07-14"
}

###

Put http://localhost:3333/collectors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlBlZHJvIiwiZW1haWwiOiJwZWRyb0BlbWFpbC5jb20iLCJiaXJ0aERhdGUiOiIxOTk1LTA3LTE0VDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3MjMzMjgwNDB9.PDJCet-uvDRQkD3qpgQe89nJISBbm0h6DKPcn5t6qE4
Content-Type: application/json

{
    "name": "Pedro Rogerio",
    "email": "pedro@email.com",
    "password": "123321",
    "birthdate": "1995-07-14"
}

###

DELETE http://localhost:3333/collectors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwibmFtZSI6IlBlZHJvIiwiZW1haWwiOiJwZWRyb0BlbWFpbC5jb20iLCJiaXJ0aERhdGUiOiIxOTk1LTA3LTE0VDAwOjAwOjAwLjAwMFoiLCJpYXQiOjE3MjMzMjgwNDB9.PDJCet-uvDRQkD3qpgQe89nJISBbm0h6DKPcn5t6qE4
Content-Type: application/json

{
    "email": "pedro@email.com"
}

###

POST http://localhost:3333/login
Content-Type: application/json

{
    "email": "pedro@email.com",
    "password": "123321"
}